### PR TITLE
Add NetBSD

### PR DESCRIPTION
**Pull request by 0323pin**
Package and merged into the main pkgsrc branch, http://mail-index.netbsd.org/pkgsrc-changes/2023/07/04/msg278153.html

Cheers!

### CODE REVIEW

**Comment by metent** [comment]
Glad to see `uair` being packaged in more repositories. I'm not super familiar with NetBSD and am assuming the change won't be live until the next release. In that case I should probably merge this after the next release of NetBSD. Please correct me if I'm wrong about how the packaging works.

**Comment by 0323pin** [comment]
> I'm not super familiar with NetBSD and am assuming the change won't be live until the next release

It's complicated 😃 but, I'll try to explain ...

First of all there's the base OS and the third-party packages, they live separate lives. You can for example run 9.3 base with stable packages, which are released 4 times per year or, you can run 9.3 with rolling packages.

You can also, as I do, run the development branch of the OS with rolling packages. Perhaps, I wouldn't recommend this set-up to a new user but, it's certainly possible and the experience is close to a bleeding-edge rolling-release distribution. I even run a bunch of self-built packages that are ahead of anything in the repositories, _e.g._ I'm using `alacritty`-0.13.0.

But, I guess you mean when `uair` will be available to users running release OS and stable packages. In which case, the answer is towards the end of September, around the 26th to be more exact. People running rolling packages will get it by next week, although this might not be the majority of the users.

Hope, it was clear. Feel free to wait until the end of September to merge this PR, I'm fine with that.

**Comment by 0323pin** [comment]
**Update:** the stable branch is due September 27.

**Comment by 0323pin** [comment]
Pling ... two days remaining.

**Comment by metent** [comment]
Sorry for the delay. LGTM

**Comment by 0323pin** [comment]
Cheers!

**Pull request merged**
