### PR TITLE
feat(uair): warn on unknown config values

### LINKED ISSUE #22: Add `#[serde(deny_unknown_fields)]` to configs
This can be quite useful as deserialization will fail in case an invalid key is added to `uair.toml`. For instance:
```toml
loop-on-end = true
# ...
```
would not work (yes, it's a real life example since I usually set TOML configs in my personal projects with `kebab-case`, so I mistakenly put this in the config and didn't realize it had no effect).

I volunteer for implementing this if it's of interest.

### PR DESCRIPTION
**Pull request by 0xangelo**
This logs warnings about unknown fields when deserializing the config, letting the user know immediately that the field is invalid.

Closes #22

### CODE REVIEW

**Comment by metent** [comment]
On further thought, this would break workflows for people who mistakenly have invalid fields in the config file. I think it would be better to warn users about all invalid fields initially rather than showing an error exiting immediately. We can use `serde_ignored` to implement this easily. Let me know what you think.

**Comment by 0xangelo** [comment]
Sure, I can look into it. How would you log warnings? `eprintln!`?

**Comment by metent** [comment]
You can use the `warn!` macro for logging. It will log the line into stderr or a file depending on a cli parameter.

**Comment by 0xangelo** [comment]
@metent I updated it. 

I had a unit test:
```rust
#[cfg(test)]
mod tests {
    use super::*;
    use toml::de::Error;

    use log::Level;

    const TOML_CFG: &str = r#"
loop-on-end = true

[defaults]
format = "{time}\n"
time_format = "%M:%S"

[[sessions]]
"#;

    #[test]
    fn unknown_config_field_warning() -> Result<(), Error> {
        testing_logger::setup();
        ConfigBuilder::deserialize(TOML_CFG)?;
        testing_logger::validate(|captured_logs| {
            assert_eq!(captured_logs.len(), 1);
            assert!(captured_logs[0]
                .body
                .contains("is not a valid config and will be ignored"));
            assert_eq!(captured_logs[0].level, Level::Warn);
        });
        Ok(())
    }
}
```
using [testing-logger](https://github.com/brucechapman/rust_testing_logger), but it conflicted with `app::tests::indicate_missing_config_file`
```
running 4 tests
test session::tests::parse_format ... ok
test app::tests::indicate_missing_config_file ... FAILED
test session::tests::parse_time_format ... ok
test config::tests::unknown_config_field_warning ... ok

failures:

---- app::tests::indicate_missing_config_file stdout ----
thread 'app::tests::indicate_missing_config_file' panicked at src/bin/uair/app.rs:340:9:
assertion `left == right` failed
  left: "Log Error: attempted to set a logger after the logging system was already initialized"
 right: "IO Error: Could not load config file \"~/.config/uair/no_uair.toml\""
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    app::tests::indicate_missing_config_file
```

I couldn't find a way to register a temporary logger to capture its output. It seems that `log` just simply doesn't support that.

**Comment by 0xangelo** [comment]
P.s.: would you be willing to add a `.rustfmt.toml` file to this repo? The default `rustfmt` nowadays (which runs automatically with most IDEs) keeps trying to format the sources here.

I used temporarily:
```toml
# .rustfmt.toml
disable_all_formatting = true
```

**Comment by 0xangelo** [comment]
P.s.2: I'd be willing to solve some `clippy` warnings too if you're interested

**Comment by metent** [comment]
> using [testing-logger](https://github.com/brucechapman/rust_testing_logger), but it conflicted with `app::tests::indicate_missing_config_file`
> 
> ```
> running 4 tests
> test session::tests::parse_format ... ok
> test app::tests::indicate_missing_config_file ... FAILED
> test session::tests::parse_time_format ... ok
> test config::tests::unknown_config_field_warning ... ok
> 
> failures:
> 
> ---- app::tests::indicate_missing_config_file stdout ----
> thread 'app::tests::indicate_missing_config_file' panicked at src/bin/uair/app.rs:340:9:
> assertion `left == right` failed
>   left: "Log Error: attempted to set a logger after the logging system was already initialized"
>  right: "IO Error: Could not load config file \"~/.config/uair/no_uair.toml\""
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> 
> 
> failures:
>     app::tests::indicate_missing_config_file
> ```
> 
> I couldn't find a way to register a temporary logger to capture its output. It seems that `log` just simply doesn't support that.

We should probably move this logger initialization code to `main`, that way we can initialize mock loggers.
https://github.com/metent/uair/blob/4ae69900bdad0ceb0fab47f41dc314fd075ba692/src/bin/uair/app.rs#L21-L33

Also, I added rustfmt.toml and applied clippy fixes, you can rebase onto main branch (or copy the code into a separate branch and set its upstream to this branch, if that's easier).

Other than that, can you document the change in the changelog? You can mention your name along with the change.

**Comment by 0xangelo** [comment]
Finally done @metent. Apologies for the long wait. Let me know if the log-related refactor is ok

**Comment by metent** [comment]
No need to apologize, most of us contribute to free software in our spare time. I'll remove the extra commented code which I assume you forgot to clean up, other than that the changes look great! Thanks!

**Comment by 0xangelo** [comment]
> No need to apologize, most of us contribute to free software in our spare time. I'll remove the extra commented code which I assume you forgot to clean up, other than that the changes look great! Thanks!

Thank you for this tool!

**Pull request merged**
